"""
Stage 4 — Fine topic labels for BERTopic v3 (359 topics post noise removal).

Structure:
  TOPIC_LABELS: dict[int, dict] — topic_id → {name, macro, sub, sub_sub}
  MACRO_CATEGORIES: list[str]   — ordered macro category names

Taxonomy layers:
  Layer 1 (macro)   — 17 categories
  Layer 2 (sub)     — 52 sub-categories
  Layer 3 (sub_sub) — 112 clusters
  Layer 4 (leaf)    — 359 fine topics (keys of TOPIC_LABELS)

Macro categories:
  1.  Vocations & Units
  2.  BMT & Training
  3.  Physical Fitness & IPPT
  4.  Medical & Health
  5.  Mental Health
  6.  NS Life & Culture
  7.  Enlistment & Pre-NS
  8.  Reservist & ICT
  9.  ORD & Post-NS
  10. Pay & Benefits
  11. Discipline & Misconduct
  12. Relationships & Social
  13. Admin & Logistics
  14. Gear & Equipment
  15. NS Policy & Society
  16. Career & Sign-on
  17. Gender & Diversity
"""

MACRO_CATEGORIES = [
    "Vocations & Units",
    "BMT & Training",
    "Physical Fitness & IPPT",
    "Medical & Health",
    "Mental Health",
    "NS Life & Culture",
    "Enlistment & Pre-NS",
    "Reservist & ICT",
    "ORD & Post-NS",
    "Pay & Benefits",
    "Discipline & Misconduct",
    "Relationships & Social",
    "Admin & Logistics",
    "Gear & Equipment",
    "NS Policy & Society",
    "Career & Sign-on",
    "Gender & Diversity",
]

TOPIC_LABELS = {
    # ── Vocations & Units ──────────────────────────────────────────────────────
    0:   {"name": "Vocational Appointments",                "macro": "Vocations & Units",        "sub": "SCDF & SPF",                     "sub_sub": "SCDF"},
    4:   {"name": "Commando/NDU Selection",                 "macro": "Vocations & Units",        "sub": "SAF Army—Combat Arms",           "sub_sub": "Elite & Special Forces"},
    12:  {"name": "Military Driving License",               "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Admin & Misc"},
    20:  {"name": "Combat Medic Vocation",                  "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Medical & Specialist Roles"},
    44:  {"name": "SCDF Firefighter Life",                  "macro": "Vocations & Units",        "sub": "SCDF & SPF",                     "sub_sub": "SCDF"},
    52:  {"name": "RSAF Pilot Selection",                   "macro": "Vocations & Units",        "sub": "RSAF",                           "sub_sub": "Pilot & Aviation"},
    55:  {"name": "Vocation by PES Status",                 "macro": "Vocations & Units",        "sub": "Vocation Guidance",              "sub_sub": "Vocation Selection"},
    57:  {"name": "Security Trooper Vocation",              "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Technical & Logistics"},
    60:  {"name": "Guards Vocation",                        "macro": "Vocations & Units",        "sub": "SAF Army—Combat Arms",           "sub_sub": "Infantry & Armour"},
    62:  {"name": "Signals Vocation",                       "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Technical & Logistics"},
    86:  {"name": "Vocation Choice & Preferences",          "macro": "Vocations & Units",        "sub": "Vocation Guidance",              "sub_sub": "Vocation Selection"},
    87:  {"name": "Infantry Battalion Culture",             "macro": "Vocations & Units",        "sub": "SAF Army—Combat Arms",           "sub_sub": "Infantry & Armour"},
    99:  {"name": "SCDF EMT/Paramedic Vocation",            "macro": "Vocations & Units",        "sub": "SCDF & SPF",                     "sub_sub": "SCDF"},
    109: {"name": "Armour Technician Vocation",             "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Technical & Logistics"},
    110: {"name": "DXO (Defence Executive Officer)",        "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Admin & Misc"},
    123: {"name": "ASA Role",                               "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Admin & Misc"},
    134: {"name": "Navy Life & Posting",                    "macro": "Vocations & Units",        "sub": "RSN (Navy)",                     "sub_sub": "Navy Life & Sea Vocations"},
    150: {"name": "Combat Engineer Vocation",               "macro": "Vocations & Units",        "sub": "SAF Army—Combat Arms",           "sub_sub": "Infantry & Armour"},
    155: {"name": "MP Vocation",                            "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Medical & Specialist Roles"},
    156: {"name": "RSAF Technician Vocation",               "macro": "Vocations & Units",        "sub": "RSAF",                           "sub_sub": "Ground & Technical"},
    158: {"name": "Rare & Unusual Vocations",               "macro": "Vocations & Units",        "sub": "Vocation Guidance",              "sub_sub": "Vocation Selection"},
    161: {"name": "ASA HQ Posting",                         "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Admin & Misc"},
    164: {"name": "RSAF Aeromedical Testing",               "macro": "Vocations & Units",        "sub": "RSAF",                           "sub_sub": "Pilot & Aviation"},
    184: {"name": "K9/Dog Handler Vocation",                "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Medical & Specialist Roles"},
    187: {"name": "Engineer Units (SCE/CBRE)",              "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Technical & Logistics"},
    208: {"name": "Ammo Depot & Supply Vocation",           "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Technical & Logistics"},
    219: {"name": "Ranger Course & SOF",                    "macro": "Vocations & Units",        "sub": "SAF Army—Combat Arms",           "sub_sub": "Elite & Special Forces"},
    223: {"name": "SAF Music & Dance Vocations",            "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Admin & Misc"},
    232: {"name": "Sniper & Recon Course",                  "macro": "Vocations & Units",        "sub": "SAF Army—Combat Arms",           "sub_sub": "Elite & Special Forces"},
    252: {"name": "Air & Naval Bases",                      "macro": "Vocations & Units",        "sub": "RSAF",                           "sub_sub": "Ground & Technical"},
    264: {"name": "Armour Vocation",                        "macro": "Vocations & Units",        "sub": "SAF Army—Combat Arms",           "sub_sub": "Infantry & Armour"},
    269: {"name": "Supply/Logistics Vocation",              "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Technical & Logistics"},
    287: {"name": "Admin Spec Role",                        "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Admin & Misc"},
    288: {"name": "IDTI/Sea Vocation",                      "macro": "Vocations & Units",        "sub": "RSN (Navy)",                     "sub_sub": "Navy Life & Sea Vocations"},
    291: {"name": "MO Cadet Course & Medical Officer",      "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Medical & Specialist Roles"},
    309: {"name": "Post-BMT Vocation Posting",              "macro": "Vocations & Units",        "sub": "Vocation Guidance",              "sub_sub": "Vocation Outcomes"},
    327: {"name": "UAV & Aviation Vocations",               "macro": "Vocations & Units",        "sub": "RSAF",                           "sub_sub": "Pilot & Aviation"},
    350: {"name": "GBAD Air Defence Vocation",              "macro": "Vocations & Units",        "sub": "RSAF",                           "sub_sub": "Ground & Technical"},
    354: {"name": "Artillery Vocation",                     "macro": "Vocations & Units",        "sub": "SAF Army—Combat Arms",           "sub_sub": "Infantry & Armour"},
    359: {"name": "Storeman Vocation",                      "macro": "Vocations & Units",        "sub": "SAF Army—Support & Services",    "sub_sub": "Admin & Misc"},
    363: {"name": "Police/HTA Officer Life",                "macro": "Vocations & Units",        "sub": "SCDF & SPF",                     "sub_sub": "SPF/HTA"},
    366: {"name": "9SIR/8SIR Battalion",                    "macro": "Vocations & Units",        "sub": "SAF Army—Combat Arms",           "sub_sub": "Infantry & Armour"},

    # ── BMT & Training ─────────────────────────────────────────────────────────
    3:   {"name": "OOC/OOT",                                "macro": "BMT & Training",           "sub": "BMT Enlistment & Life",          "sub_sub": "BMT Structure & Phases"},
    6:   {"name": "Outfield Training",                      "macro": "BMT & Training",           "sub": "Field & Combat Training",        "sub_sub": "Outfield Experience"},
    7:   {"name": "Mono Intake & BMT Vocation Posting",     "macro": "BMT & Training",           "sub": "BMT Enlistment & Life",          "sub_sub": "BMT Structure & Phases"},
    14:  {"name": "BMT General Experience",                 "macro": "BMT & Training",           "sub": "BMT Enlistment & Life",          "sub_sub": "BMT Structure & Phases"},
    16:  {"name": "OCS/SCS Officer Cadet Life",             "macro": "BMT & Training",           "sub": "Officer & NCO Training",         "sub_sub": "OCS/SCS"},
    26:  {"name": "Pulau Tekong",                           "macro": "BMT & Training",           "sub": "BMT Enlistment & Life",          "sub_sub": "Tekong Life"},
    29:  {"name": "SCS Infantry Training",                  "macro": "BMT & Training",           "sub": "Officer & NCO Training",         "sub_sub": "OCS/SCS"},
    33:  {"name": "Route March",                            "macro": "BMT & Training",           "sub": "Field & Combat Training",        "sub_sub": "Physical Courses"},
    34:  {"name": "POP Ceremony",                           "macro": "BMT & Training",           "sub": "BMT Enlistment & Life",          "sub_sub": "BMT Structure & Phases"},
    64:  {"name": "SCS/OCS Leadership Training",            "macro": "BMT & Training",           "sub": "Officer & NCO Training",         "sub_sub": "OCS/SCS"},
    72:  {"name": "PTP (Physical Training Phase)",          "macro": "BMT & Training",           "sub": "BMT Enlistment & Life",          "sub_sub": "PTP"},
    91:  {"name": "Shooting & Marksmanship",                "macro": "BMT & Training",           "sub": "Field & Combat Training",        "sub_sub": "Weapons & Shooting"},
    92:  {"name": "BMT Recourse & Re-BMT",                  "macro": "BMT & Training",           "sub": "BMT Enlistment & Life",          "sub_sub": "BMT Structure & Phases"},
    126: {"name": "Exercise Wallaby (Australia)",           "macro": "BMT & Training",           "sub": "Field & Combat Training",        "sub_sub": "Exercise & Detachment"},
    129: {"name": "Tekong Life & Tekan",                    "macro": "BMT & Training",           "sub": "BMT Enlistment & Life",          "sub_sub": "Tekong Life"},
    163: {"name": "Tekong Illness (Cough/Flu)",             "macro": "BMT & Training",           "sub": "BMT Enlistment & Life",          "sub_sub": "Tekong Life"},
    186: {"name": "Overseas Exercises",                     "macro": "BMT & Training",           "sub": "Field & Combat Training",        "sub_sub": "Exercise & Detachment"},
    194: {"name": "SAR21 Handling",                         "macro": "BMT & Training",           "sub": "Field & Combat Training",        "sub_sub": "Weapons & Shooting"},
    201: {"name": "Weapons Handling & Safety",              "macro": "BMT & Training",           "sub": "Field & Combat Training",        "sub_sub": "Weapons & Shooting"},
    204: {"name": "SOC (Standard Obstacle Course)",         "macro": "BMT & Training",           "sub": "Field & Combat Training",        "sub_sub": "Physical Courses"},
    231: {"name": "SCS Company Culture & Welfare",          "macro": "BMT & Training",           "sub": "Officer & NCO Training",         "sub_sub": "OCS/SCS"},
    243: {"name": "BMT Phases by PES",                      "macro": "BMT & Training",           "sub": "BMT Enlistment & Life",          "sub_sub": "BMT Structure & Phases"},
    250: {"name": "BMT Platoon Stories",                    "macro": "BMT & Training",           "sub": "BMT Enlistment & Life",          "sub_sub": "BMT Culture & Stories"},
    259: {"name": "Tekong Enlistment Day",                  "macro": "BMT & Training",           "sub": "BMT Enlistment & Life",          "sub_sub": "Tekong Life"},
    276: {"name": "CQB & Field Combat Skills",              "macro": "BMT & Training",           "sub": "Field & Combat Training",        "sub_sub": "Outfield Experience"},
    302: {"name": "Outfield Sanitation & Defecation",       "macro": "BMT & Training",           "sub": "Field & Combat Training",        "sub_sub": "Outfield Experience"},
    315: {"name": "PTP Weight & BMI",                       "macro": "BMT & Training",           "sub": "BMT Enlistment & Life",          "sub_sub": "PTP"},
    323: {"name": "ATEC & Field Exercises",                 "macro": "BMT & Training",           "sub": "Field & Combat Training",        "sub_sub": "Physical Courses"},
    336: {"name": "Left-Handed Rifle Handling",             "macro": "BMT & Training",           "sub": "Field & Combat Training",        "sub_sub": "Weapons & Shooting"},
    364: {"name": "CSB & Crossing Badge",                   "macro": "BMT & Training",           "sub": "Field & Combat Training",        "sub_sub": "Physical Courses"},
    368: {"name": "Tekong Water & Food",                    "macro": "BMT & Training",           "sub": "BMT Enlistment & Life",          "sub_sub": "Tekong Life"},

    # ── Physical Fitness & IPPT ────────────────────────────────────────────────
    18:  {"name": "BMI & Weight Issues",                    "macro": "Physical Fitness & IPPT",  "sub": "Weight & Nutrition",             "sub_sub": "Weight Management"},
    56:  {"name": "Pre-Enlistment IPPT/PTP",                "macro": "Physical Fitness & IPPT",  "sub": "Weight & Nutrition",             "sub_sub": "Weight Management"},
    76:  {"name": "Running Training",                       "macro": "Physical Fitness & IPPT",  "sub": "Physical Training",              "sub_sub": "Running & Cardio"},
    115: {"name": "Pushup & Situp Training",                "macro": "Physical Fitness & IPPT",  "sub": "Physical Training",              "sub_sub": "Strength Training"},
    120: {"name": "Running & Endurance Training",           "macro": "Physical Fitness & IPPT",  "sub": "Physical Training",              "sub_sub": "Running & Cardio"},
    122: {"name": "Swimming in NS",                         "macro": "Physical Fitness & IPPT",  "sub": "Physical Training",              "sub_sub": "Running & Cardio"},
    132: {"name": "NSFit IPPT Sessions",                    "macro": "Physical Fitness & IPPT",  "sub": "IPPT",                           "sub_sub": "IPPT Training & RT"},
    149: {"name": "IPPT Pass/Fail",                         "macro": "Physical Fitness & IPPT",  "sub": "IPPT",                           "sub_sub": "IPPT Standards & Booking"},
    172: {"name": "IPPT RT & Remedial Training",            "macro": "Physical Fitness & IPPT",  "sub": "IPPT",                           "sub_sub": "IPPT Training & RT"},
    173: {"name": "IPPT Scoring & Standards",               "macro": "Physical Fitness & IPPT",  "sub": "IPPT",                           "sub_sub": "IPPT Standards & Booking"},
    196: {"name": "IPPT Window Booking",                    "macro": "Physical Fitness & IPPT",  "sub": "IPPT",                           "sub_sub": "IPPT Standards & Booking"},
    209: {"name": "Pushup Reps & Training",                 "macro": "Physical Fitness & IPPT",  "sub": "Physical Training",              "sub_sub": "Strength Training"},
    222: {"name": "General Fitness Training",               "macro": "Physical Fitness & IPPT",  "sub": "Physical Training",              "sub_sub": "Strength Training"},
    280: {"name": "IPPT Stations & Venues",                 "macro": "Physical Fitness & IPPT",  "sub": "IPPT",                           "sub_sub": "IPPT Standards & Booking"},
    281: {"name": "Nutrition for IPPT",                     "macro": "Physical Fitness & IPPT",  "sub": "Weight & Nutrition",             "sub_sub": "Nutrition & Supplements"},
    307: {"name": "Camp Gym",                               "macro": "Physical Fitness & IPPT",  "sub": "Physical Training",              "sub_sub": "Strength Training"},
    345: {"name": "Protein & Muscle Gain",                  "macro": "Physical Fitness & IPPT",  "sub": "Weight & Nutrition",             "sub_sub": "Nutrition & Supplements"},
    365: {"name": "NSFit Programme",                        "macro": "Physical Fitness & IPPT",  "sub": "IPPT",                           "sub_sub": "IPPT Training & RT"},

    # ── Medical & Health ───────────────────────────────────────────────────────
    5:   {"name": "PES Status due to Medical Conditions",    "macro": "Medical & Health",         "sub": "PES & Downgrade",                "sub_sub": "PES Status & Codes"},
    15:  {"name": "PES Status Codes",                       "macro": "Medical & Health",         "sub": "PES & Downgrade",                "sub_sub": "PES Status & Codes"},
    25:  {"name": "COVID & Vaccination",                    "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Skin Allergies & Misc"},
    27:  {"name": "Physical Injuries",                      "macro": "Medical & Health",         "sub": "Injuries & Surgery",             "sub_sub": "Physical Injuries"},
    32:  {"name": "Medical Appointments & Memos",           "macro": "Medical & Health",         "sub": "Medical Admin",                  "sub_sub": "MC & Sick Leave"},
    35:  {"name": "Medical Claims & 11B Coverage",          "macro": "Medical & Health",         "sub": "Medical Admin",                  "sub_sub": "Claims & Documentation"},
    41:  {"name": "Dental Procedures",                      "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Dental & Eye"},
    70:  {"name": "Skin Conditions & Downpes",              "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Skin Allergies & Misc"},
    80:  {"name": "RSO/RSI Status",                         "macro": "Medical & Health",         "sub": "Medical Admin",                  "sub_sub": "MC & Sick Leave"},
    116: {"name": "Dental Claims & Coverage",               "macro": "Medical & Health",         "sub": "Medical Admin",                  "sub_sub": "Claims & Documentation"},
    124: {"name": "Kranji Camp (PES C/E)",                  "macro": "Medical & Health",         "sub": "PES & Downgrade",                "sub_sub": "Status Changes & Revocation"},
    148: {"name": "Hearing Loss & Earplugs",                "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Skin Allergies & Misc"},
    160: {"name": "Medical Screening (STD/Blood Check)",    "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Skin Allergies & Misc"},
    166: {"name": "Asthma & Respiratory Conditions",        "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Chronic & Developmental Conditions"},
    171: {"name": "Service Injury Compensation",            "macro": "Medical & Health",         "sub": "Injuries & Surgery",             "sub_sub": "Physical Injuries"},
    181: {"name": "Acne & Skin Medication",                 "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Medication"},
    192: {"name": "Myopia & Eyesight Issues",                "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Chronic & Developmental Conditions"},
    198: {"name": "Braces & Cosmetic Dental",               "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Dental & Eye"},
    202: {"name": "Slipped Disc & Back Injury",             "macro": "Medical & Health",         "sub": "Injuries & Surgery",             "sub_sub": "Physical Injuries"},
    205: {"name": "FFI (Final Medical Inspection)",         "macro": "Medical & Health",         "sub": "Medical Admin",                  "sub_sub": "Claims & Documentation"},
    213: {"name": "Medical Officer & Clinic Visits",        "macro": "Medical & Health",         "sub": "Medical Admin",                  "sub_sub": "MC & Sick Leave"},
    217: {"name": "PT Excuse",                               "macro": "Medical & Health",         "sub": "Medical Admin",                  "sub_sub": "Medical Excuses"},
    226: {"name": "Cardiac & ECG Conditions",               "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Chronic & Developmental Conditions"},
    238: {"name": "Downpes Process",                        "macro": "Medical & Health",         "sub": "PES & Downgrade",                "sub_sub": "Downpes Process"},
    240: {"name": "Skincare & Sun Protection",              "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Medication"},
    256: {"name": "Sick Reporting Procedure",               "macro": "Medical & Health",         "sub": "Medical Admin",                  "sub_sub": "MC & Sick Leave"},
    260: {"name": "ADHD & Neurodevelopmental Conditions",   "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Chronic & Developmental Conditions"},
    262: {"name": "Medical Advice",                         "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Skin Allergies & Misc"},
    265: {"name": "Downpes Discussion (Social)",            "macro": "Medical & Health",         "sub": "PES & Downgrade",                "sub_sub": "Downpes Process"},
    298: {"name": "Firearms Excuse Status",                 "macro": "Medical & Health",         "sub": "Medical Admin",                  "sub_sub": "Medical Excuses"},
    299: {"name": "BMT Recourse & Downpes",                 "macro": "Medical & Health",         "sub": "PES & Downgrade",                "sub_sub": "Downpes Process"},
    300: {"name": "Colour Blindness",                       "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Chronic & Developmental Conditions"},
    306: {"name": "Light Duty Excuse",                      "macro": "Medical & Health",         "sub": "Medical Admin",                  "sub_sub": "Medical Excuses"},
    311: {"name": "Surgery & Recovery",                     "macro": "Medical & Health",         "sub": "Injuries & Surgery",             "sub_sub": "Surgery & Recovery"},
    312: {"name": "Autism & ASD in NS",                     "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Chronic & Developmental Conditions"},
    313: {"name": "LASIK & Eye Surgery",                    "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Dental & Eye"},
    321: {"name": "Scoliosis & Spinal Issues",              "macro": "Medical & Health",         "sub": "Injuries & Surgery",             "sub_sub": "Physical Injuries"},
    328: {"name": "Bringing Medication to Camp",            "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Medication"},
    338: {"name": "Status Revocation",                      "macro": "Medical & Health",         "sub": "PES & Downgrade",                "sub_sub": "Status Changes & Revocation"},
    346: {"name": "Cancer & Serious Illness",               "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Chronic & Developmental Conditions"},
    355: {"name": "Combat Medic OOC",                       "macro": "Medical & Health",         "sub": "Injuries & Surgery",             "sub_sub": "Surgery & Recovery"},
    367: {"name": "Fever & Flu Symptoms",                   "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Skin Allergies & Misc"},
    371: {"name": "Allergies",                              "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Skin Allergies & Misc"},
    374: {"name": "Dust/Allergy Excuse",                    "macro": "Medical & Health",         "sub": "Conditions & Specialist Care",   "sub_sub": "Skin Allergies & Misc"},

    # ── Mental Health ──────────────────────────────────────────────────────────
    67:  {"name": "Mental Health Support Seeking",          "macro": "Mental Health",            "sub": "Clinical & Psychiatric",         "sub_sub": "Help Seeking & Declaration"},
    75:  {"name": "Psychiatric Referral Process",           "macro": "Mental Health",            "sub": "Clinical & Psychiatric",         "sub_sub": "Psychiatric Referral & IMH"},
    104: {"name": "IMH & Psychiatrist Referral",            "macro": "Mental Health",            "sub": "Clinical & Psychiatric",         "sub_sub": "Psychiatric Referral & IMH"},
    235: {"name": "Pre-Enlistment Anxiety",                  "macro": "Mental Health",            "sub": "Wellbeing & Anxiety",            "sub_sub": "Anxiety"},
    247: {"name": "Mental Health Declaration & Help",       "macro": "Mental Health",            "sub": "Clinical & Psychiatric",         "sub_sub": "Help Seeking & Declaration"},
    272: {"name": "In-Camp Mental Wellbeing",               "macro": "Mental Health",            "sub": "Wellbeing & Anxiety",            "sub_sub": "In-Camp Wellbeing"},
    370: {"name": "Adjustment Disorder & Downpes",          "macro": "Mental Health",            "sub": "Clinical & Psychiatric",         "sub_sub": "Psychiatric Referral & IMH"},

    # ── NS Life & Culture ──────────────────────────────────────────────────────
    1:   {"name": "Cookhouse Food",                         "macro": "NS Life & Culture",        "sub": "Daily Camp Life",                "sub_sub": "Food & Cookhouse"},
    10:  {"name": "Bookout & Confinement",                  "macro": "NS Life & Culture",        "sub": "Time Off & Personal Life",       "sub_sub": "Bookout & Leave"},
    11:  {"name": "Leave & Block Leave",                    "macro": "NS Life & Culture",        "sub": "Time Off & Personal Life",       "sub_sub": "Bookout & Leave"},
    13:  {"name": "General NS Life Reflections",            "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "NS Identity & Reflections"},
    28:  {"name": "Ghost Stories & Tekong Superstitions",   "macro": "NS Life & Culture",        "sub": "Duties & Responsibilities",      "sub_sub": "Misc Camp Admin"},
    38:  {"name": "Guard Duty",                             "macro": "NS Life & Culture",        "sub": "Duties & Responsibilities",      "sub_sub": "Duties"},
    43:  {"name": "Sleep Issues in NS",                     "macro": "NS Life & Culture",        "sub": "Daily Camp Life",                "sub_sub": "Camp Environment"},
    59:  {"name": "Mobile Data & Signal in Camp",           "macro": "NS Life & Culture",        "sub": "Daily Camp Life",                "sub_sub": "Camp Environment"},
    65:  {"name": "Encik / Warrant Officer Stories",        "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "Encik & Commander Stories"},
    81:  {"name": "Unit/Platoon Anecdotes",                 "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "NS Identity & Reflections"},
    84:  {"name": "Generic Advice & Support Posts",         "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Generic Advice & Support"},
    96:  {"name": "Commander-Subordinate Relations",        "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Unit & Platoon Dynamics"},
    98:  {"name": "Bunkmates & Buddy System",               "macro": "NS Life & Culture",        "sub": "Daily Camp Life",                "sub_sub": "Bunk & Living Conditions"},
    103: {"name": "Laundry in Camp",                        "macro": "NS Life & Culture",        "sub": "Daily Camp Life",                "sub_sub": "Bunk & Living Conditions"},
    106: {"name": "Wildlife in Camp",                       "macro": "NS Life & Culture",        "sub": "Daily Camp Life",                "sub_sub": "Camp Environment"},
    111: {"name": "Toilets & Showers in Camp",              "macro": "NS Life & Culture",        "sub": "Daily Camp Life",                "sub_sub": "Bunk & Living Conditions"},
    114: {"name": "SAF General Banter",                     "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "NS Humour & Banter"},
    130: {"name": "Company Welfare & Culture",              "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Unit & Platoon Dynamics"},
    135: {"name": "Giving Up Seats in Uniform",             "macro": "NS Life & Culture",        "sub": "Duties & Responsibilities",      "sub_sub": "NS Public Life"},
    141: {"name": "Friendships Made in NS",                 "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Friendships & Bonds"},
    143: {"name": "Studying During NS",                     "macro": "NS Life & Culture",        "sub": "Time Off & Personal Life",       "sub_sub": "Bookout & Leave"},
    146: {"name": "Thanks & Gratitude Replies",             "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Generic Advice & Support"},
    151: {"name": "NDP Contingent",                         "macro": "NS Life & Culture",        "sub": "Duties & Responsibilities",      "sub_sub": "NS Public Life"},
    162: {"name": "NS Songs & Marching Songs",              "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "NS Identity & Reflections"},
    169: {"name": "Generic NS Advice",                      "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Generic Advice & Support"},
    174: {"name": "Being Blur / Acting Sotong",             "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "NS Humour & Banter"},
    177: {"name": "Duty Excusal & Night Offs",              "macro": "NS Life & Culture",        "sub": "Duties & Responsibilities",      "sub_sub": "Duties"},
    189: {"name": "Boot Polishing",                         "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "NS Humour & Banter"},
    193: {"name": "Duty during Holiday/Festive Periods",    "macro": "NS Life & Culture",        "sub": "Duties & Responsibilities",      "sub_sub": "Duties"},
    203: {"name": "Encik Quotes & Stories",                 "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "Encik & Commander Stories"},
    221: {"name": "Learnet & Camp Tablets",                 "macro": "NS Life & Culture",        "sub": "Duties & Responsibilities",      "sub_sub": "Misc Camp Admin"},
    230: {"name": "Bunk Conditions (Aircon/Fans)",          "macro": "NS Life & Culture",        "sub": "Daily Camp Life",                "sub_sub": "Bunk & Living Conditions"},
    233: {"name": "MLM & Insurance Recruitment",            "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Generic Advice & Support"},
    242: {"name": "Being a Spec / Sergeant",                "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Unit & Platoon Dynamics"},
    245: {"name": "Platoon Dynamics & Stories",             "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Unit & Platoon Dynamics"},
    253: {"name": "Mosquitoes & Insect Repellent",          "macro": "NS Life & Culture",        "sub": "Daily Camp Life",                "sub_sub": "Camp Environment"},
    266: {"name": "Workplace Conflicts with Superiors",     "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Unit & Platoon Dynamics"},
    273: {"name": "Stay-out Arrangement",                   "macro": "NS Life & Culture",        "sub": "Time Off & Personal Life",       "sub_sub": "Bookout & Leave"},
    274: {"name": "Wayang in NS",                           "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "NS Humour & Banter"},
    275: {"name": "NSF vs Regular Comparisons",             "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Unit & Platoon Dynamics"},
    278: {"name": "Specific Commander Stories",             "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "Encik & Commander Stories"},
    283: {"name": "Letters to/from Camp",                   "macro": "NS Life & Culture",        "sub": "Duties & Responsibilities",      "sub_sub": "Misc Camp Admin"},
    284: {"name": "BMT Friendships",                        "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Friendships & Bonds"},
    285: {"name": "Batch & Intake Numbers",                 "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "NS Identity & Reflections"},
    289: {"name": "Work Hours & Off Days",                  "macro": "NS Life & Culture",        "sub": "Time Off & Personal Life",       "sub_sub": "Bookout & Leave"},
    293: {"name": "Officer Life in NS",                     "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Unit & Platoon Dynamics"},
    294: {"name": "Encik Grandma Jokes",                    "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "Encik & Commander Stories"},
    295: {"name": "Wearing Camo in Public",                 "macro": "NS Life & Culture",        "sub": "Duties & Responsibilities",      "sub_sub": "NS Public Life"},
    303: {"name": "Bunk Nudity",                            "macro": "NS Life & Culture",        "sub": "Daily Camp Life",                "sub_sub": "Bunk & Living Conditions"},
    304: {"name": "Public Holidays & Off-in-Lieu",          "macro": "NS Life & Culture",        "sub": "Time Off & Personal Life",       "sub_sub": "Bookout & Leave"},
    310: {"name": "NS Movies & Media (Ah Boys to Men)",     "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "NS Humour & Banter"},
    322: {"name": "Saluting & Addressing Officers",         "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "NS Identity & Reflections"},
    324: {"name": "Gaming & PC Setup Post-Bookout",         "macro": "NS Life & Culture",        "sub": "Duties & Responsibilities",      "sub_sub": "NS Public Life"},
    329: {"name": "OCS Milo Stories",                       "macro": "NS Life & Culture",        "sub": "NS Culture & Humour",            "sub_sub": "NS Identity & Reflections"},
    333: {"name": "Company Mottos & Culture",               "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Unit & Platoon Dynamics"},
    334: {"name": "JB Trips & Malaysia Border",             "macro": "NS Life & Culture",        "sub": "Duties & Responsibilities",      "sub_sub": "NS Public Life"},
    337: {"name": "Bunk & Dorm Life",                       "macro": "NS Life & Culture",        "sub": "Daily Camp Life",                "sub_sub": "Bunk & Living Conditions"},
    352: {"name": "Generic Congratulations/GG Posts",       "macro": "NS Life & Culture",        "sub": "Social & Interpersonal",         "sub_sub": "Generic Advice & Support"},

    # ── Enlistment & Pre-NS ────────────────────────────────────────────────────
    9:   {"name": "Enlistment Haircut",                     "macro": "Enlistment & Pre-NS",      "sub": "Enlistment Process",             "sub_sub": "Pre-Enlistment Prep"},
    24:  {"name": "Packing Preparations",                    "macro": "Enlistment & Pre-NS",      "sub": "Enlistment Process",             "sub_sub": "Pre-Enlistment Prep"},
    39:  {"name": "Enlistment Anxiety & Camaraderie",       "macro": "Enlistment & Pre-NS",      "sub": "Enlistment Process",             "sub_sub": "Pre-Enlistment Prep"},
    42:  {"name": "NS Disruption for University",           "macro": "Enlistment & Pre-NS",      "sub": "Deferment & Disruption",         "sub_sub": "Academic Deferment"},
    63:  {"name": "Enlistment Date & CMPB",                 "macro": "Enlistment & Pre-NS",      "sub": "Enlistment Process",             "sub_sub": "CMPB & Enlistment Admin"},
    78:  {"name": "NS Deferment for Studies",               "macro": "Enlistment & Pre-NS",      "sub": "Deferment & Disruption",         "sub_sub": "Academic Deferment"},
    90:  {"name": "Tattoos & Piercings",                    "macro": "Enlistment & Pre-NS",      "sub": "Enlistment Process",             "sub_sub": "Pre-Enlistment Prep"},
    113: {"name": "Pre-NS Cadet Programmes",                "macro": "Enlistment & Pre-NS",      "sub": "Enlistment Process",             "sub_sub": "Pre-Enlistment Prep"},
    179: {"name": "PES at Enlistment",                      "macro": "Enlistment & Pre-NS",      "sub": "Physical & Medical Pre-NS",      "sub_sub": "PES at Enlistment"},
    182: {"name": "Enlistment Letter & Date",               "macro": "Enlistment & Pre-NS",      "sub": "Enlistment Process",             "sub_sub": "CMPB & Enlistment Admin"},
    211: {"name": "Pre-Enlistment Discussion",              "macro": "Enlistment & Pre-NS",      "sub": "Enlistment Process",             "sub_sub": "CMPB & Enlistment Admin"},
    212: {"name": "Height & Physical Requirements",         "macro": "Enlistment & Pre-NS",      "sub": "Physical & Medical Pre-NS",      "sub_sub": "PES at Enlistment"},
    270: {"name": "Medical Disruption (LMDS)",              "macro": "Enlistment & Pre-NS",      "sub": "Deferment & Disruption",         "sub_sub": "Medical Disruption"},

    # ── Reservist & ICT ────────────────────────────────────────────────────────
    23:  {"name": "Reservist Callup",                       "macro": "Reservist & ICT",          "sub": "ICT Structure & Life",           "sub_sub": "Callup & Mobilisation"},
    88:  {"name": "Mobilisation & Activation",               "macro": "Reservist & ICT",          "sub": "ICT Structure & Life",           "sub_sub": "Callup & Mobilisation"},
    137: {"name": "ICT Cycles",                              "macro": "Reservist & ICT",          "sub": "ICT Structure & Life",           "sub_sub": "ICT Cycles & Keys"},
    140: {"name": "Reservist Life",                          "macro": "Reservist & ICT",          "sub": "ICT Structure & Life",           "sub_sub": "ICT Cycles & Keys"},
    199: {"name": "ICT High/Low Keys",                       "macro": "Reservist & ICT",          "sub": "ICT Structure & Life",           "sub_sub": "ICT Cycles & Keys"},
    206: {"name": "Reservist Pay & MUP Claims",             "macro": "Reservist & ICT",          "sub": "ICT Admin",                      "sub_sub": "Pay & Medical"},
    220: {"name": "ICT Deferment",                          "macro": "Reservist & ICT",          "sub": "ICT Admin",                      "sub_sub": "Deferment"},
    244: {"name": "Reservist Deferment",                    "macro": "Reservist & ICT",          "sub": "ICT Admin",                      "sub_sub": "Deferment"},
    362: {"name": "ICT Injury & Medical Excuse",            "macro": "Reservist & ICT",          "sub": "ICT Admin",                      "sub_sub": "Pay & Medical"},

    # ── ORD & Post-NS ──────────────────────────────────────────────────────────
    21:  {"name": "Post-NS Education & Career",             "macro": "ORD & Post-NS",            "sub": "Post-ORD Life",                  "sub_sub": "Education & Career"},
    47:  {"name": "ORD Mood & Countdown",                   "macro": "ORD & Post-NS",            "sub": "ORD Countdown",                  "sub_sub": "Countdown & Mood"},
    49:  {"name": "ORD Countdown",                          "macro": "ORD & Post-NS",            "sub": "ORD Countdown",                  "sub_sub": "Countdown & Mood"},
    121: {"name": "PR/Citizenship Application Post-ORD",    "macro": "ORD & Post-NS",            "sub": "Post-ORD Life",                  "sub_sub": "Life After NS"},
    138: {"name": "NS Testimonial & Conduct Grade",         "macro": "ORD & Post-NS",            "sub": "ORD Admin",                      "sub_sub": "ORD Clearance"},
    190: {"name": "Housing & Property (Post-NS)",           "macro": "ORD & Post-NS",            "sub": "Post-ORD Life",                  "sub_sub": "Life After NS"},
    191: {"name": "Extended ORD Date",                       "macro": "ORD & Post-NS",            "sub": "ORD Admin",                      "sub_sub": "ORD Clearance"},
    249: {"name": "NRIC & SingPass on ORD",                 "macro": "ORD & Post-NS",            "sub": "ORD Admin",                      "sub_sub": "ORD Clearance"},
    267: {"name": "ORD Countdown Apps",                     "macro": "ORD & Post-NS",            "sub": "ORD Countdown",                  "sub_sub": "Countdown & Mood"},
    282: {"name": "ORD Laojiao Countdown",                  "macro": "ORD & Post-NS",            "sub": "ORD Countdown",                  "sub_sub": "Countdown & Mood"},
    308: {"name": "NS & Career Skills",                     "macro": "ORD & Post-NS",            "sub": "Post-ORD Life",                  "sub_sub": "Education & Career"},

    # ── Pay & Benefits ─────────────────────────────────────────────────────────
    31:  {"name": "LifeSG Credits & NS Benefits",           "macro": "Pay & Benefits",           "sub": "NS Credits & Benefits",          "sub_sub": "NS Credits & eMart"},
    53:  {"name": "NSF Pay & Allowance",                    "macro": "Pay & Benefits",           "sub": "NSF Pay",                        "sub_sub": "Pay Rates & Crediting"},
    69:  {"name": "Pay Crediting & Banking",                "macro": "Pay & Benefits",           "sub": "NSF Pay",                        "sub_sub": "Pay Rates & Crediting"},
    105: {"name": "Saving NSF Allowance",                   "macro": "Pay & Benefits",           "sub": "Personal Finance",               "sub_sub": "Savings & Investments"},
    107: {"name": "eMart & NS Credits",                     "macro": "Pay & Benefits",           "sub": "NS Credits & Benefits",          "sub_sub": "NS Credits & eMart"},
    168: {"name": "Investing NSF Allowance",                "macro": "Pay & Benefits",           "sub": "Personal Finance",               "sub_sub": "Savings & Investments"},
    176: {"name": "Pay Rates by Rank",                      "macro": "Pay & Benefits",           "sub": "NSF Pay",                        "sub_sub": "Pay Rates & Crediting"},
    178: {"name": "Transport Concession & Fare",            "macro": "Pay & Benefits",           "sub": "NSF Pay",                        "sub_sub": "Transport & Concessions"},
    200: {"name": "NS ePREP & Learning Credits",            "macro": "Pay & Benefits",           "sub": "NS Credits & Benefits",          "sub_sub": "NS Credits & eMart"},
    227: {"name": "Transport Claims",                       "macro": "Pay & Benefits",           "sub": "NSF Pay",                        "sub_sub": "Transport & Concessions"},
    236: {"name": "NS Group Insurance Coverage",            "macro": "Pay & Benefits",           "sub": "NS Credits & Benefits",          "sub_sub": "SAFRA & Insurance"},
    254: {"name": "SAFRA Membership & Benefits",            "macro": "Pay & Benefits",           "sub": "NS Credits & Benefits",          "sub_sub": "SAFRA & Insurance"},
    316: {"name": "Holiday Pay & Festive Duties",           "macro": "Pay & Benefits",           "sub": "NSF Pay",                        "sub_sub": "Pay Rates & Crediting"},
    326: {"name": "Side Income & Trading",                  "macro": "Pay & Benefits",           "sub": "Personal Finance",               "sub_sub": "Savings & Investments"},
    343: {"name": "eMart Locations & Deals",                "macro": "Pay & Benefits",           "sub": "NS Credits & Benefits",          "sub_sub": "NS Credits & eMart"},

    # ── Discipline & Misconduct ────────────────────────────────────────────────
    17:  {"name": "DB & Military Charges",                  "macro": "Discipline & Misconduct",  "sub": "Charges & Punishment",           "sub_sub": "DB & Formal Charges"},
    22:  {"name": "Chao Keng / Skiving",                    "macro": "Discipline & Misconduct",  "sub": "Rules & Violations",             "sub_sub": "Skiving & Malingering"},
    50:  {"name": "Smoking & Vaping in NS",                 "macro": "Discipline & Misconduct",  "sub": "Rules & Violations",             "sub_sub": "Surveillance & Restrictions"},
    54:  {"name": "MC Usage & Endorsement",                 "macro": "Discipline & Misconduct",  "sub": "Rules & Violations",             "sub_sub": "Skiving & Malingering"},
    66:  {"name": "Moonlighting During NS",                 "macro": "Discipline & Misconduct",  "sub": "Rules & Violations",             "sub_sub": "Theft & Off-duty Breaches"},
    131: {"name": "Sexual Misconduct Reports",              "macro": "Discipline & Misconduct",  "sub": "Misconduct & Harassment",        "sub_sub": "Bullying & Harassment"},
    139: {"name": "Phone Checks by MPs",                    "macro": "Discipline & Misconduct",  "sub": "Rules & Violations",             "sub_sub": "Surveillance & Restrictions"},
    142: {"name": "Taking Photos in Camp",                  "macro": "Discipline & Misconduct",  "sub": "Rules & Violations",             "sub_sub": "Surveillance & Restrictions"},
    145: {"name": "Home Stay & Visits during MC",            "macro": "Discipline & Misconduct",  "sub": "Rules & Violations",             "sub_sub": "Skiving & Malingering"},
    159: {"name": "Bullying in NS",                         "macro": "Discipline & Misconduct",  "sub": "Misconduct & Harassment",        "sub_sub": "Bullying & Harassment"},
    175: {"name": "Extra Duties & Punishment",              "macro": "Discipline & Misconduct",  "sub": "Charges & Punishment",           "sub_sub": "Extra Duties & Punishment"},
    277: {"name": "Urine & Drug Test",                       "macro": "Discipline & Misconduct",  "sub": "Rules & Violations",             "sub_sub": "Surveillance & Restrictions"},
    290: {"name": "Malingering Charges",                    "macro": "Discipline & Misconduct",  "sub": "Rules & Violations",             "sub_sub": "Skiving & Malingering"},
    314: {"name": "Malingering & DB Charges",               "macro": "Discipline & Misconduct",  "sub": "Charges & Punishment",           "sub_sub": "DB & Formal Charges"},
    340: {"name": "Theft & Stolen Items in Camp",           "macro": "Discipline & Misconduct",  "sub": "Rules & Violations",             "sub_sub": "Theft & Off-duty Breaches"},
    369: {"name": "Sexual Harassment Discussion",           "macro": "Discipline & Misconduct",  "sub": "Misconduct & Harassment",        "sub_sub": "Bullying & Harassment"},
    373: {"name": "Reporting Misconduct Up Chain",          "macro": "Discipline & Misconduct",  "sub": "Misconduct & Harassment",        "sub_sub": "Reporting Up Chain"},

    # ── Relationships & Social ─────────────────────────────────────────────────
    8:   {"name": "Relationships During NS",                "macro": "Relationships & Social",   "sub": "Romantic Relationships",         "sub_sub": "Dating & Relationships"},
    85:  {"name": "Gifts for Partner During NS",             "macro": "Relationships & Social",   "sub": "Romantic Relationships",         "sub_sub": "Gifts & Milestones"},
    216: {"name": "POP Day Gifts for BF",                   "macro": "Relationships & Social",   "sub": "Romantic Relationships",         "sub_sub": "Gifts & Milestones"},
    319: {"name": "Dating While in NS",                     "macro": "Relationships & Social",   "sub": "Romantic Relationships",         "sub_sub": "Dating & Relationships"},
    331: {"name": "Relationship Breakups During NS",        "macro": "Relationships & Social",   "sub": "Romantic Relationships",         "sub_sub": "Dating & Relationships"},
    357: {"name": "Marriage & Kids During NS",               "macro": "Relationships & Social",   "sub": "Romantic Relationships",         "sub_sub": "Dating & Relationships"},
    358: {"name": "Infidelity During NS",                   "macro": "Relationships & Social",   "sub": "Romantic Relationships",         "sub_sub": "Dating & Relationships"},

    # ── Admin & Logistics ──────────────────────────────────────────────────────
    19:  {"name": "Unit Posting Expectations",              "macro": "Admin & Logistics",        "sub": "Documentation & Clearance",      "sub_sub": "Posting & Vocation Admin"},
    37:  {"name": "Rank Promotion",                         "macro": "Admin & Logistics",        "sub": "Rank & Structure",               "sub_sub": "Rank Hierarchy"},
    45:  {"name": "Powerbank & Charging in Camp",           "macro": "Admin & Logistics",        "sub": "Camp & Personal Admin",          "sub_sub": "Personal Items & Electronics"},
    46:  {"name": "Camp Locations & Transport",             "macro": "Admin & Logistics",        "sub": "Camp & Personal Admin",          "sub_sub": "Transport & Camps"},
    74:  {"name": "Phone & Camera Restrictions",            "macro": "Admin & Logistics",        "sub": "Camp & Personal Admin",          "sub_sub": "Personal Items & Electronics"},
    95:  {"name": "Spectacles & Eyewear Claims",            "macro": "Admin & Logistics",        "sub": "Camp & Personal Admin",          "sub_sub": "Personal Items & Electronics"},
    100: {"name": "Lost 11B & NRIC",                        "macro": "Admin & Logistics",        "sub": "Documentation & Clearance",      "sub_sub": "Personnel Systems"},
    101: {"name": "Exit Permits",                            "macro": "Admin & Logistics",        "sub": "Documentation & Clearance",      "sub_sub": "Personnel Systems"},
    165: {"name": "Bringing Electronics to Camp",           "macro": "Admin & Logistics",        "sub": "Camp & Personal Admin",          "sub_sub": "Personal Items & Electronics"},
    188: {"name": "Driving to Camp & Parking",              "macro": "Admin & Logistics",        "sub": "Camp & Personal Admin",          "sub_sub": "Transport & Camps"},
    197: {"name": "Vocation Posting Results",               "macro": "Admin & Logistics",        "sub": "Documentation & Clearance",      "sub_sub": "Posting & Vocation Admin"},
    228: {"name": "Security Clearance",                     "macro": "Admin & Logistics",        "sub": "Documentation & Clearance",      "sub_sub": "Security & Clearance"},
    246: {"name": "Rank Structure & Hierarchy",             "macro": "Admin & Logistics",        "sub": "Rank & Structure",               "sub_sub": "Rank Hierarchy"},
    251: {"name": "NS Portal & App Issues",                 "macro": "Admin & Logistics",        "sub": "Documentation & Clearance",      "sub_sub": "Personnel Systems"},
    296: {"name": "Camp Transfer Requests",                 "macro": "Admin & Logistics",        "sub": "Rank & Structure",               "sub_sub": "Unit & Platoon Structure"},
    297: {"name": "Camp Locations Discussion",              "macro": "Admin & Logistics",        "sub": "Camp & Personal Admin",          "sub_sub": "Transport & Camps"},
    301: {"name": "Unit Posting & Transfer",                "macro": "Admin & Logistics",        "sub": "Documentation & Clearance",      "sub_sub": "Posting & Vocation Admin"},
    305: {"name": "Earphones & Music in Camp",              "macro": "Admin & Logistics",        "sub": "Camp & Personal Admin",          "sub_sub": "Personal Items & Electronics"},
    318: {"name": "Junior NCO Ranks (LCP/CPL)",             "macro": "Admin & Logistics",        "sub": "Rank & Structure",               "sub_sub": "Rank Hierarchy"},
    320: {"name": "G50 Security Form",                      "macro": "Admin & Logistics",        "sub": "Documentation & Clearance",      "sub_sub": "Security & Clearance"},
    335: {"name": "Platoon & Company Structure",            "macro": "Admin & Logistics",        "sub": "Rank & Structure",               "sub_sub": "Unit & Platoon Structure"},
    339: {"name": "ISAC Card & Personnel Systems",          "macro": "Admin & Logistics",        "sub": "Documentation & Clearance",      "sub_sub": "Personnel Systems"},
    356: {"name": "Warrant Officers & WOSpec",              "macro": "Admin & Logistics",        "sub": "Rank & Structure",               "sub_sub": "Rank Hierarchy"},

    # ── Gear & Equipment ───────────────────────────────────────────────────────
    108: {"name": "Watches & Wearables",                    "macro": "Gear & Equipment",         "sub": "Personal Gear",                  "sub_sub": "Wearables & Accessories"},
    112: {"name": "Name Tags & Sewing",                     "macro": "Gear & Equipment",         "sub": "Field Gear & Kit",               "sub_sub": "Field Equipment"},
    125: {"name": "Smart4 Uniform Regulations",             "macro": "Gear & Equipment",         "sub": "Uniform & Dress",                "sub_sub": "Uniform Regulations"},
    144: {"name": "Boots & Footwear",                       "macro": "Gear & Equipment",         "sub": "Field Gear & Kit",               "sub_sub": "Boots & Footwear"},
    152: {"name": "Helmets & Webbing",                      "macro": "Gear & Equipment",         "sub": "Field Gear & Kit",               "sub_sub": "Field Equipment"},
    153: {"name": "Wearing Uniform (Types & Rules)",        "macro": "Gear & Equipment",         "sub": "Uniform & Dress",                "sub_sub": "Uniform Regulations"},
    183: {"name": "Headdress & Cap Regulations",            "macro": "Gear & Equipment",         "sub": "Uniform & Dress",                "sub_sub": "Headgear & Berets"},
    185: {"name": "PT Kit & Underwear",                     "macro": "Gear & Equipment",         "sub": "Uniform & Dress",                "sub_sub": "Uniform Regulations"},
    214: {"name": "Jungle Hat & Recon Headgear",            "macro": "Gear & Equipment",         "sub": "Uniform & Dress",                "sub_sub": "Headgear & Berets"},
    225: {"name": "Sports Shoes & Running Gear",            "macro": "Gear & Equipment",         "sub": "Field Gear & Kit",               "sub_sub": "Boots & Footwear"},
    229: {"name": "Civilian Attire Rules",                  "macro": "Gear & Equipment",         "sub": "Uniform & Dress",                "sub_sub": "Uniform Regulations"},
    248: {"name": "Beret Colours & Insignia",               "macro": "Gear & Equipment",         "sub": "Uniform & Dress",                "sub_sub": "Headgear & Berets"},
    271: {"name": "Beret Seasoning & Maintenance",           "macro": "Gear & Equipment",         "sub": "Uniform & Dress",                "sub_sub": "Headgear & Berets"},
    286: {"name": "Formation Patches & Badges",             "macro": "Gear & Equipment",         "sub": "Field Gear & Kit",               "sub_sub": "Field Equipment"},
    292: {"name": "OCS PT Attire",                          "macro": "Gear & Equipment",         "sub": "Uniform & Dress",                "sub_sub": "Uniform Regulations"},
    332: {"name": "Admin Tee & Clothing",                   "macro": "Gear & Equipment",         "sub": "Uniform & Dress",                "sub_sub": "Uniform Regulations"},
    347: {"name": "Load Bearing Vest & Pouches",            "macro": "Gear & Equipment",         "sub": "Field Gear & Kit",               "sub_sub": "Field Equipment"},

    # ── NS Policy & Society ────────────────────────────────────────────────────
    2:   {"name": "Gender & Conscription Debate",           "macro": "NS Policy & Society",      "sub": "Conscription & National Duty",   "sub_sub": "Conscription Debate"},
    30:  {"name": "NS National Duty Discourse",             "macro": "NS Policy & Society",      "sub": "Conscription & National Duty",   "sub_sub": "Conscription Debate"},
    36:  {"name": "Sports Deferment & Athletes",            "macro": "NS Policy & Society",      "sub": "Conscription & National Duty",   "sub_sub": "Conscription Debate"},
    48:  {"name": "NS-Related Scams",                       "macro": "NS Policy & Society",      "sub": "Safety & Incidents",             "sub_sub": "Scams"},
    51:  {"name": "NS Deaths & Training Incidents",         "macro": "NS Policy & Society",      "sub": "Safety & Incidents",             "sub_sub": "Training Incidents"},
    61:  {"name": "Singapore Politics & NS Policy",         "macro": "NS Policy & Society",      "sub": "Geopolitics & Defence",          "sub_sub": "Singapore Defence"},
    82:  {"name": "Conscription Policy Debate",             "macro": "NS Policy & Society",      "sub": "Conscription & National Duty",   "sub_sub": "Conscription Debate"},
    83:  {"name": "PR/Citizenship & NS Obligation",         "macro": "NS Policy & Society",      "sub": "PR & Foreign Nationals",         "sub_sub": "PR & Citizenship Obligation"},
    154: {"name": "Global Conscription Comparison",         "macro": "NS Policy & Society",      "sub": "Conscription & National Duty",   "sub_sub": "Conscription Debate"},
    157: {"name": "Singapore Geopolitics & Defence",        "macro": "NS Policy & Society",      "sub": "Geopolitics & Defence",          "sub_sub": "Singapore Defence"},
    167: {"name": "War & National Defence",                 "macro": "NS Policy & Society",      "sub": "Geopolitics & Defence",          "sub_sub": "Singapore Defence"},
    215: {"name": "Enlistment Age",                         "macro": "NS Policy & Society",      "sub": "Conscription & National Duty",   "sub_sub": "Conscription Debate"},
    218: {"name": "Voting Age & NS",                        "macro": "NS Policy & Society",      "sub": "Conscription & National Duty",   "sub_sub": "Conscription Debate"},
    224: {"name": "Safety Reporting & Counselling Hotline", "macro": "NS Policy & Society",      "sub": "Safety & Incidents",             "sub_sub": "Reporting & Hotlines"},
    234: {"name": "Aloysius Pang Incident",                 "macro": "NS Policy & Society",      "sub": "Safety & Incidents",             "sub_sub": "Training Incidents"},
    239: {"name": "PR Renouncing NS",                       "macro": "NS Policy & Society",      "sub": "PR & Foreign Nationals",         "sub_sub": "PR & Citizenship Obligation"},
    241: {"name": "SAF Safety Concerns",                    "macro": "NS Policy & Society",      "sub": "Safety & Incidents",             "sub_sub": "Training Incidents"},
    263: {"name": "Generational Difference in NS",           "macro": "NS Policy & Society",      "sub": "Conscription & National Duty",   "sub_sub": "NS Identity & Society"},
    279: {"name": "ADF/Foreign Military Service",           "macro": "NS Policy & Society",      "sub": "PR & Foreign Nationals",         "sub_sub": "Foreign Military"},
    330: {"name": "NSmen Identity & Status",                "macro": "NS Policy & Society",      "sub": "Conscription & National Duty",   "sub_sub": "NS Identity & Society"},
    341: {"name": "Ukraine War & Global Conflict",          "macro": "NS Policy & Society",      "sub": "Geopolitics & Defence",          "sub_sub": "Global Conflicts"},
    342: {"name": "Serving Singapore & Overseas PRs",       "macro": "NS Policy & Society",      "sub": "PR & Foreign Nationals",         "sub_sub": "PR & Citizenship Obligation"},
    349: {"name": "White Horse Preferential Treatment",     "macro": "NS Policy & Society",      "sub": "Conscription & National Duty",   "sub_sub": "NS Identity & Society"},
    361: {"name": "Singapore Defence & Security",           "macro": "NS Policy & Society",      "sub": "Geopolitics & Defence",          "sub_sub": "Singapore Defence"},

    # ── Career & Sign-on ───────────────────────────────────────────────────────
    40:  {"name": "SAF Scholarship & Sign-on",              "macro": "Career & Sign-on",         "sub": "Officer & Scholarship Paths",    "sub_sub": "Scholarships & Commissions"},
    93:  {"name": "Signing On as Regular",                  "macro": "Career & Sign-on",         "sub": "Regular & Contract Service",     "sub_sub": "Regular Army & Navy/Air Force"},
    118: {"name": "CyberNSF Scheme",                        "macro": "Career & Sign-on",         "sub": "Officer & Scholarship Paths",    "sub_sub": "Cyber & Specialist Schemes"},
    133: {"name": "C4I/Cyber Specialist Schemes",           "macro": "Career & Sign-on",         "sub": "Officer & Scholarship Paths",    "sub_sub": "Cyber & Specialist Schemes"},
    136: {"name": "Navy/Air Force Career Sign-on",          "macro": "Career & Sign-on",         "sub": "Regular & Contract Service",     "sub_sub": "Regular Army & Navy/Air Force"},
    170: {"name": "EOS/WOSpec Scheme",                      "macro": "Career & Sign-on",         "sub": "Regular & Contract Service",     "sub_sub": "Contract Schemes"},
    180: {"name": "Short-Term Contract (STC/VES)",          "macro": "Career & Sign-on",         "sub": "Regular & Contract Service",     "sub_sub": "Contract Schemes"},
    210: {"name": "ME Scheme (Military Expert)",            "macro": "Career & Sign-on",         "sub": "Regular & Contract Service",     "sub_sub": "Contract Schemes"},
    258: {"name": "Regular Army Career Life",               "macro": "Career & Sign-on",         "sub": "Regular & Contract Service",     "sub_sub": "Regular Army & Navy/Air Force"},
    317: {"name": "OCS/SCS Officer Sign-on",                "macro": "Career & Sign-on",         "sub": "Officer & Scholarship Paths",    "sub_sub": "Scholarships & Commissions"},
    325: {"name": "Signing On During BMT",                  "macro": "Career & Sign-on",         "sub": "Officer & Scholarship Paths",    "sub_sub": "Scholarships & Commissions"},
    351: {"name": "VES Contract Extension",                 "macro": "Career & Sign-on",         "sub": "Regular & Contract Service",     "sub_sub": "Contract Schemes"},
    353: {"name": "Army Career & Sign-on",                  "macro": "Career & Sign-on",         "sub": "Regular & Contract Service",     "sub_sub": "Regular Army & Navy/Air Force"},
    360: {"name": "MDES Scheme",                            "macro": "Career & Sign-on",         "sub": "Officer & Scholarship Paths",    "sub_sub": "Cyber & Specialist Schemes"},

    # ── Gender & Diversity ─────────────────────────────────────────────────────
    68:  {"name": "LGBT & Sexuality in NS",                 "macro": "Gender & Diversity",       "sub": "Gender & Sexuality",             "sub_sub": "LGBT & Identity"},
    73:  {"name": "Female Regular Soldiers",                "macro": "Gender & Diversity",       "sub": "Gender & Sexuality",             "sub_sub": "Women in NS"},
    102: {"name": "Race & Language in NS",                  "macro": "Gender & Diversity",       "sub": "Race & Religion",                "sub_sub": "Race & Language"},
    119: {"name": "Transgender in NS",                      "macro": "Gender & Diversity",       "sub": "Gender & Sexuality",             "sub_sub": "LGBT & Identity"},
    147: {"name": "Religion & Prayer in NS",                "macro": "Gender & Diversity",       "sub": "Race & Religion",                "sub_sub": "Race & Language"},
    237: {"name": "Race & Religion in NS (Malay/Muslim)",   "macro": "Gender & Diversity",       "sub": "Race & Religion",                "sub_sub": "Race & Language"},
    268: {"name": "Gender Dynamics in NS Context",          "macro": "Gender & Diversity",       "sub": "Gender & Sexuality",             "sub_sub": "Conscription & Gender"},
    344: {"name": "Racial Slurs & Racism in NS",            "macro": "Gender & Diversity",       "sub": "Race & Religion",                "sub_sub": "Race & Language"},
    348: {"name": "Toxic Masculinity in NS",                 "macro": "Gender & Diversity",       "sub": "Gender & Sexuality",             "sub_sub": "Conscription & Gender"},
}
